# Generated by Django 3.0.6 on 2020-10-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_food_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
