# Generated by Django 3.0.6 on 2020-10-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201007_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item',
            name='cuisine',
        ),
    ]
