# Generated by Django 3.0.6 on 2020-10-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
            preserve_default=False,
        ),
    ]
