# Generated by Django 3.0.6 on 2020-10-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='item_price_total',
            field=models.CharField(max_length=100),
        ),
    ]
