# Generated by Django 3.0.6 on 2020-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20201007_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='invoice not generated', max_length=10),
        ),
    ]
