# Generated by Django 3.0.6 on 2020-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20201008_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='inovoicenotegenrated', max_length=50),
        ),
    ]
