# Generated by Django 3.0.6 on 2020-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20201008_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoiceGenerated',
            field=models.BooleanField(default=0),
        ),
    ]
