# Generated by Django 3.0.6 on 2020-10-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20201008_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoiceGenerated',
        ),
    ]
