# Generated by Django 3.0.6 on 2020-10-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_order_invoicegenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoiceGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
